# Generated by Django 6.1 on 2026-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='source',
            field=models.CharField(default='', max_length=20),
        ),
    ]
